### PR TITLE
Release/going live

### PR DESCRIPTION
**Pull request by ptusch**
Preapre for go-live.
Minor version bumps, changelog and proper readme display on npmjs.org

### CODE REVIEW

**Review by Radu94 — COMMENTED** [review]
Maybe also remove the "^" anchors from package.json dependencies and update the [readme section about deployment](https://github.com/6labs/openldapjs/tree/release/going_live#deployment) , since now we can  npm install  and require it nicely :)
Other than that looks good to me :D

**Comment by ptusch** [comment]
@Radu94 You have quite the eagle eyes - added your changes please have a second look!

**Comment by Radu94** [comment]
@ptusch the line with **_This section should be updated as soon as we properly package it_**. is no longer needed now, other than that it looks good to me :)

**Review by Radu94 — APPROVED** [review]

**Comment by Radu94** [comment]
@ptusch  seems like i wasn't thorough, my bad 
https://github.com/6labs/openldapjs/tree/release/going_live/docs#usage <- still has a TODO and the require will get  this export: `
module.exports = {
  Client: LdapClient,
  errorHandler: errorHandler,
  errorList: errorList,
};
`
Now i'm like 60% sure i didn't miss anything :) my apologies.

**Pull request merged**
